import { useRef, useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  const inputRef = useRef();
  const [shortURL, setShortURL] = useState("");

  const handleSubmit = (e) => {
    e.preventDefault();
    const url = inputRef.current.value;

    fetch("/api/shortUrl", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ url }),
    })
      .then((res) => res.json())
      .then((data) => {
        setShortURL(data.shortUrl);
      });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>URL Shortener</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          <img
            src="/undraw_link_shortener_mvf6.svg"
            alt="URL Shortener"
            className={styles.image}
          />
          <span className="title-color-primary"> URL </span>{" "}
          <span className="title-color-secundary"> Shortener </span>
        </h1>
        <p className={styles.description}>Acorta tus URLs aquí</p>
        <form className={styles.card} onSubmit={handleSubmit}>
          <input
            ref={inputRef}
            type="text"
            className={styles.input}
            placeholder="Ingresa tu URL"
          />
          <button className={styles.button}>Acortar</button>

        </form>
        <p><b>Resultado : </b>  <span className={styles.input}>{shortURL}</span></p>
      </main>
    </div>
  );
}
